stages:
  validate:
    cmd: python data_validation.py
    deps:
      - data_validation.py
      - data_raw/bank-additional.csv
    outs:
      - validation_passed.txt:
          cache: false
  train:
    cmd: python model_training.py
    deps:
      - model_training.py
      - data_raw/bank-additional.csv
      - validation_passed.txt
    outs:
      - model.pkl:
          cache: false
      - columns_info.json:
          cache: false
    metrics:
      - model_metadata.json:
          cache: false
